### ISSUE TITLE
MIDI host via USB?

### ISSUE THREAD

**Issue by talondnb** [max22-/ESP32-BLE-MIDI#4]
Apologies if I'm misinterpreting the usage of this package, but I have a Casio Privia PX-770 that has a type B USB class compliant port that typically can be plugged into a MIDI host for MIDI usage (e.g. iPad or Mac/PC software). What I'm trying to do is see if the Casio type B USB can be plugged into a ESP32, which can then be used to transmit MIDI over BLE to a host (e.g. iPad or Mac/PC). So type B USB <> micro USB on ESP32, then BLE wirelessly to host.

Is this possible? Thanks in advance.

**Comment by max22-** [comment]
Only the ESP32-S2 has USB support. You could use this library to receive data from your usb midi device : https://github.com/hathach/tinyusb, and then use ESP32-BLE-MIDI to transmit via BLE. But the usb part will be tricky I think.

So, will it be possible ? maybe. but it will be difficult.
If you decide to try it,start with the BLE part to verify that there is no problem with it, because some people have reported problems when it acts as a client. And I don't have corrected this problem yet.

Good luck
